CREATE TABLE [tbl_wrk_Route_Species] (
  [Unit_Code] VARCHAR (4),
  [Visit_Year] SHORT ,
  [Species] VARCHAR (50),
  [Common_Name] VARCHAR (50),
  [Columbus Canyon(3)PlotCount] SHORT ,
  [Columbus Canyon(3)CoverPct] DOUBLE ,
  [Columbus Canyon(3) (SE)] DOUBLE ,
  [East Glade Park Road(18)PlotCount] SHORT ,
  [East Glade Park Road(18)CoverPct] DOUBLE ,
  [East Glade Park Road(18) (SE)] DOUBLE ,
  [Fenceline Route(28)PlotCount] SHORT ,
  [Fenceline Route(28)CoverPct] DOUBLE ,
  [Fenceline Route(28) (SE)] DOUBLE ,
  [Fruita Canyon(4)PlotCount] SHORT ,
  [Fruita Canyon(4)CoverPct] DOUBLE ,
  [Fruita Canyon(4) (SE)] DOUBLE ,
  [Gold Star Canyon(3)PlotCount] SHORT ,
  [Gold Star Canyon(3)CoverPct] DOUBLE ,
  [Gold Star Canyon(3) (SE)] DOUBLE ,
  [Hydro 03(1)PlotCount] SHORT ,
  [Hydro 03(1)CoverPct] DOUBLE ,
  [Hydro 03(1) (SE)] DOUBLE ,
  [Hydro 11(2)PlotCount] SHORT ,
  [Hydro 11(2)CoverPct] DOUBLE ,
  [Hydro 11(2) (SE)] DOUBLE ,
  [Hydro 85(1)PlotCount] SHORT ,
  [Hydro 85(1)CoverPct] DOUBLE ,
  [Hydro 85(1) (SE)] DOUBLE ,
  [Hydro 95(5)PlotCount] SHORT ,
  [Hydro 95(5)CoverPct] DOUBLE ,
  [Hydro 95(5) (SE)] DOUBLE ,
  [Kodels Canyon(1)PlotCount] SHORT ,
  [Kodels Canyon(1)CoverPct] DOUBLE ,
  [Kodels Canyon(1) (SE)] DOUBLE ,
  [Kodels Canyon Route(2)PlotCount] SHORT ,
  [Kodels Canyon Route(2)CoverPct] DOUBLE ,
  [Kodels Canyon Route(2) (SE)] DOUBLE ,
  [Liberty Cap Trail(14)PlotCount] SHORT ,
  [Liberty Cap Trail(14)CoverPct] DOUBLE ,
  [Liberty Cap Trail(14) (SE)] DOUBLE ,
  [Limekin Gulch(1)PlotCount] SHORT ,
  [Limekin Gulch(1)CoverPct] DOUBLE ,
  [Limekin Gulch(1) (SE)] DOUBLE ,
  [Lizard Canyon(2)PlotCount] SHORT ,
  [Lizard Canyon(2)CoverPct] DOUBLE ,
  [Lizard Canyon(2) (SE)] DOUBLE ,
  [Monument Canyon(18)PlotCount] SHORT ,
  [Monument Canyon(18)CoverPct] DOUBLE ,
  [Monument Canyon(18) (SE)] DOUBLE ,
  [Monument Canyon Trail(15)PlotCount] SHORT ,
  [Monument Canyon Trail(15)CoverPct] DOUBLE ,
  [Monument Canyon Trail(15) (SE)] DOUBLE ,
  [No Thoroughfare Canyon(13)PlotCount] SHORT ,
  [No Thoroughfare Canyon(13)CoverPct] DOUBLE ,
  [No Thoroughfare Canyon(13) (SE)] DOUBLE ,
  [No Thoroughfare Trail(8)PlotCount] SHORT ,
  [No Thoroughfare Trail(8)CoverPct] DOUBLE ,
  [No Thoroughfare Trail(8) (SE)] DOUBLE ,
  [Red Canyon(8)PlotCount] SHORT ,
  [Red Canyon(8)CoverPct] DOUBLE ,
  [Red Canyon(8) (SE)] DOUBLE ,
  [Rim Rock Drive(23)PlotCount] SHORT ,
  [Rim Rock Drive(23)CoverPct] DOUBLE ,
  [Rim Rock Drive(23) (SE)] DOUBLE ,
  [Rim Rock Drive, E Glade Park Rd to Ute Canyon Vi(17)PlotCount] SHORT ,
  [Rim Rock Drive, E Glade Park Rd to Ute Canyon Vi(17)CoverPct] DOUBLE ,
  [Rim Rock Drive, E Glade Park Rd to Ute Canyon Vi(17) (SE)] DOUBLE ,
  [Ute Canyon(14)PlotCount] SHORT ,
  [Ute Canyon(14)CoverPct] DOUBLE ,
  [Ute Canyon(14) (SE)] DOUBLE ,
  [Wedding Canyon(6)PlotCount] SHORT ,
  [Wedding Canyon(6)CoverPct] DOUBLE ,
  [Wedding Canyon(6) (SE)] DOUBLE 
)
