CREATE TABLE [tbl_wrk_Route_Species] (
  [Unit_Code] VARCHAR (4),
  [Visit_Year] SHORT ,
  [Species] VARCHAR (50),
  [Common_Name] VARCHAR (50),
  [Archeology Trail(1)PlotCount] SHORT ,
  [Archeology Trail(1)CoverPct] DOUBLE ,
  [Archeology Trail(1) (SE)] DOUBLE ,
  [Chinle Trail(11)PlotCount] SHORT ,
  [Chinle Trail(11)CoverPct] DOUBLE ,
  [Chinle Trail(11) (SE)] DOUBLE ,
  [Grotto Trail(2)PlotCount] SHORT ,
  [Grotto Trail(2)CoverPct] DOUBLE ,
  [Grotto Trail(2) (SE)] DOUBLE ,
  [Hop Valley Trail(4)PlotCount] SHORT ,
  [Hop Valley Trail(4)CoverPct] DOUBLE ,
  [Hop Valley Trail(4) (SE)] DOUBLE ,
  [Kayenta Trail(2)PlotCount] SHORT ,
  [Kayenta Trail(2)CoverPct] DOUBLE ,
  [Kayenta Trail(2) (SE)] DOUBLE ,
  [Kolob Scenic Drive(34)PlotCount] SHORT ,
  [Kolob Scenic Drive(34)CoverPct] DOUBLE ,
  [Kolob Scenic Drive(34) (SE)] DOUBLE ,
  [La Verkin Creek Trail(4)PlotCount] SHORT ,
  [La Verkin Creek Trail(4)CoverPct] DOUBLE ,
  [La Verkin Creek Trail(4) (SE)] DOUBLE ,
  [Lower Emerald Pools Trail(2)PlotCount] SHORT ,
  [Lower Emerald Pools Trail(2)CoverPct] DOUBLE ,
  [Lower Emerald Pools Trail(2) (SE)] DOUBLE ,
  [Middle Emerald Pools Trail(1)PlotCount] SHORT ,
  [Middle Emerald Pools Trail(1)CoverPct] DOUBLE ,
  [Middle Emerald Pools Trail(1) (SE)] DOUBLE ,
  [Middle Taylor Creek Trail(6)PlotCount] SHORT ,
  [Middle Taylor Creek Trail(6)CoverPct] DOUBLE ,
  [Middle Taylor Creek Trail(6) (SE)] DOUBLE ,
  [Riverside Walk(3)PlotCount] SHORT ,
  [Riverside Walk(3)CoverPct] DOUBLE ,
  [Riverside Walk(3) (SE)] DOUBLE ,
  [Sand Bench Trail(14)PlotCount] SHORT ,
  [Sand Bench Trail(14)CoverPct] DOUBLE ,
  [Sand Bench Trail(14) (SE)] DOUBLE ,
  [State Route 9(39)PlotCount] SHORT ,
  [State Route 9(39)CoverPct] DOUBLE ,
  [State Route 9(39) (SE)] DOUBLE ,
  [Upper Emerald Pools Trail(1)PlotCount] SHORT ,
  [Upper Emerald Pools Trail(1)CoverPct] DOUBLE ,
  [Upper Emerald Pools Trail(1) (SE)] DOUBLE ,
  [Upper Kolob Terrace Road(26)PlotCount] SHORT ,
  [Upper Kolob Terrace Road(26)CoverPct] DOUBLE ,
  [Upper Kolob Terrace Road(26) (SE)] DOUBLE ,
  [Watchman Trail(5)PlotCount] SHORT ,
  [Watchman Trail(5)CoverPct] DOUBLE ,
  [Watchman Trail(5) (SE)] DOUBLE ,
  [West Rim Trail(16)PlotCount] SHORT ,
  [West Rim Trail(16)CoverPct] DOUBLE ,
  [West Rim Trail(16) (SE)] DOUBLE ,
  [Wrangler Trail(3)PlotCount] SHORT ,
  [Wrangler Trail(3)CoverPct] DOUBLE ,
  [Wrangler Trail(3) (SE)] DOUBLE 
)
