CREATE TABLE [xtbl_wrk_Route_Species] (
  [Unit_Code] VARCHAR (4),
  [Visit_Year] SHORT ,
  [Species] VARCHAR (50),
  [Common_Name] VARCHAR (50),
  [Columbus Canyon(4)PlotCount] SHORT ,
  [Columbus Canyon(4)CoverPct] DOUBLE ,
  [Columbus Canyon(4) (SE)] DOUBLE ,
  [East Glade Park Road(16)PlotCount] SHORT ,
  [East Glade Park Road(16)CoverPct] DOUBLE ,
  [East Glade Park Road(16) (SE)] DOUBLE ,
  [Fruita Canyon(4)PlotCount] SHORT ,
  [Fruita Canyon(4)CoverPct] DOUBLE ,
  [Fruita Canyon(4) (SE)] DOUBLE ,
  [Gold Star Canyon(4)PlotCount] SHORT ,
  [Gold Star Canyon(4)CoverPct] DOUBLE ,
  [Gold Star Canyon(4) (SE)] DOUBLE ,
  [Hydro 03(1)PlotCount] SHORT ,
  [Hydro 03(1)CoverPct] DOUBLE ,
  [Hydro 03(1) (SE)] DOUBLE ,
  [Hydro 11(3)PlotCount] SHORT ,
  [Hydro 11(3)CoverPct] DOUBLE ,
  [Hydro 11(3) (SE)] DOUBLE ,
  [Hydro 82(1)PlotCount] SHORT ,
  [Hydro 82(1)CoverPct] DOUBLE ,
  [Hydro 82(1) (SE)] DOUBLE ,
  [Hydro 85(1)PlotCount] SHORT ,
  [Hydro 85(1)CoverPct] DOUBLE ,
  [Hydro 85(1) (SE)] DOUBLE ,
  [Hydro 86(2)PlotCount] SHORT ,
  [Hydro 86(2)CoverPct] DOUBLE ,
  [Hydro 86(2) (SE)] DOUBLE ,
  [Hydro 88(1)PlotCount] SHORT ,
  [Hydro 88(1)CoverPct] DOUBLE ,
  [Hydro 88(1) (SE)] DOUBLE ,
  [Hydro 95(4)PlotCount] SHORT ,
  [Hydro 95(4)CoverPct] DOUBLE ,
  [Hydro 95(4) (SE)] DOUBLE ,
  [Kodels Canyon(1)PlotCount] SHORT ,
  [Kodels Canyon(1)CoverPct] DOUBLE ,
  [Kodels Canyon(1) (SE)] DOUBLE ,
  [Kodels Canyon Route(2)PlotCount] SHORT ,
  [Kodels Canyon Route(2)CoverPct] DOUBLE ,
  [Kodels Canyon Route(2) (SE)] DOUBLE ,
  [Lizard Canyon(3)PlotCount] SHORT ,
  [Lizard Canyon(3)CoverPct] DOUBLE ,
  [Lizard Canyon(3) (SE)] DOUBLE ,
  [Monument Canyon(19)PlotCount] SHORT ,
  [Monument Canyon(19)CoverPct] DOUBLE ,
  [Monument Canyon(19) (SE)] DOUBLE ,
  [No Thoroughfare Canyon(18)PlotCount] SHORT ,
  [No Thoroughfare Canyon(18)CoverPct] DOUBLE ,
  [No Thoroughfare Canyon(18) (SE)] DOUBLE ,
  [No Thoroughfare Trail(2)PlotCount] SHORT ,
  [No Thoroughfare Trail(2)CoverPct] DOUBLE ,
  [No Thoroughfare Trail(2) (SE)] DOUBLE ,
  [Red Canyon(8)PlotCount] SHORT ,
  [Red Canyon(8)CoverPct] DOUBLE ,
  [Red Canyon(8) (SE)] DOUBLE ,
  [Rim Rock Drive(24)PlotCount] SHORT ,
  [Rim Rock Drive(24)CoverPct] DOUBLE ,
  [Rim Rock Drive(24) (SE)] DOUBLE ,
  [Rim Rock Drive, E Glade Park Rd to Ute Canyon Vi(18)PlotCount] SHORT ,
  [Rim Rock Drive, E Glade Park Rd to Ute Canyon Vi(18)CoverPct] DOUBLE ,
  [Rim Rock Drive, E Glade Park Rd to Ute Canyon Vi(18) (SE)] DOUBLE ,
  [Ute Canyon(14)PlotCount] SHORT ,
  [Ute Canyon(14)CoverPct] DOUBLE ,
  [Ute Canyon(14) (SE)] DOUBLE ,
  [Wedding Canyon(6)PlotCount] SHORT ,
  [Wedding Canyon(6)CoverPct] DOUBLE ,
  [Wedding Canyon(6) (SE)] DOUBLE 
)
