CREATE TABLE [ZION_2015_TCount] (
  [Unit_Code] VARCHAR (4),
  [Visit_Year] SHORT ,
  [Species] VARCHAR (255),
  [Master_Common_Name] VARCHAR (255),
  [Alive?] VARCHAR (255),
  [Archeology Trail (1) TCount] LONG ,
  [Cable Mountain Trail (6) TCount] LONG ,
  [Chinle Trail (19) TCount] LONG ,
  [Deertrap Mountain Trail (13) TCount] LONG ,
  [East Mesa Trail (14) TCount] LONG ,
  [East Rim Trail (34) TCount] LONG ,
  [Grotto Trail (2) TCount] LONG ,
  [Kolob Scenic Drive (36) TCount] LONG ,
  [Middle Taylor Creek Trail (4) TCount] LONG ,
  [Museum Trail (1) TCount] LONG ,
  [Oak Creek and Administrative (8) TCount] LONG ,
  [Parus Trail (5) TCount] LONG ,
  [Riverside Walk (3) TCount] LONG ,
  [Sand Bench Trail (15) TCount] LONG ,
  [State Route 9 (44) TCount] LONG ,
  [Stave Spring (2) TCount] LONG ,
  [Timber Creek Overlook Trail (2) TCount] LONG ,
  [Upper Emerald Pools Trail (1) TCount] LONG ,
  [Watchman Housing and PTI (2) TCount] LONG ,
  [Watchman Trail (7) TCount] LONG ,
  [Weeping Rock (1) TCount] LONG ,
  [West Rim Trail (15) TCount] LONG ,
  [Wrangler Trail (4) TCount] LONG ,
  [Zion Scenic Drive (42) TCount] LONG 
)
