CREATE TABLE [ZION_2015_SE] (
  [Unit_Code] VARCHAR (4),
  [Visit_Year] SHORT ,
  [Species] VARCHAR (255),
  [Master_Common_Name] VARCHAR (255),
  [Alive?] VARCHAR (255),
  [Archeology Trail (1) SE] DOUBLE ,
  [Cable Mountain Trail (6) SE] DOUBLE ,
  [Chinle Trail (19) SE] DOUBLE ,
  [Deertrap Mountain Trail (13) SE] DOUBLE ,
  [East Mesa Trail (14) SE] DOUBLE ,
  [East Rim Trail (34) SE] DOUBLE ,
  [Grotto Trail (2) SE] DOUBLE ,
  [Kolob Scenic Drive (36) SE] DOUBLE ,
  [Middle Taylor Creek Trail (4) SE] DOUBLE ,
  [Museum Trail (1) SE] DOUBLE ,
  [Oak Creek and Administrative (8) SE] DOUBLE ,
  [Parus Trail (5) SE] DOUBLE ,
  [Riverside Walk (3) SE] DOUBLE ,
  [Sand Bench Trail (15) SE] DOUBLE ,
  [State Route 9 (44) SE] DOUBLE ,
  [Stave Spring (2) SE] DOUBLE ,
  [Timber Creek Overlook Trail (2) SE] DOUBLE ,
  [Upper Emerald Pools Trail (1) SE] DOUBLE ,
  [Watchman Housing and PTI (2) SE] DOUBLE ,
  [Watchman Trail (7) SE] DOUBLE ,
  [Weeping Rock (1) SE] DOUBLE ,
  [West Rim Trail (15) SE] DOUBLE ,
  [Wrangler Trail (4) SE] DOUBLE ,
  [Zion Scenic Drive (42) SE] DOUBLE 
)
