CREATE TABLE [ZION_2015_PctCover] (
  [Unit_Code] VARCHAR (4),
  [Visit_Year] SHORT ,
  [Species] VARCHAR (255),
  [Master_Common_Name] VARCHAR (255),
  [Alive?] VARCHAR (255),
  [Archeology Trail (1) PctCover] DOUBLE ,
  [Cable Mountain Trail (6) PctCover] DOUBLE ,
  [Chinle Trail (19) PctCover] DOUBLE ,
  [Deertrap Mountain Trail (13) PctCover] DOUBLE ,
  [East Mesa Trail (14) PctCover] DOUBLE ,
  [East Rim Trail (34) PctCover] DOUBLE ,
  [Grotto Trail (2) PctCover] DOUBLE ,
  [Kolob Scenic Drive (36) PctCover] DOUBLE ,
  [Middle Taylor Creek Trail (4) PctCover] DOUBLE ,
  [Museum Trail (1) PctCover] DOUBLE ,
  [Oak Creek and Administrative (8) PctCover] DOUBLE ,
  [Parus Trail (5) PctCover] DOUBLE ,
  [Riverside Walk (3) PctCover] DOUBLE ,
  [Sand Bench Trail (15) PctCover] DOUBLE ,
  [State Route 9 (44) PctCover] DOUBLE ,
  [Stave Spring (2) PctCover] DOUBLE ,
  [Timber Creek Overlook Trail (2) PctCover] DOUBLE ,
  [Upper Emerald Pools Trail (1) PctCover] DOUBLE ,
  [Watchman Housing and PTI (2) PctCover] DOUBLE ,
  [Watchman Trail (7) PctCover] DOUBLE ,
  [Weeping Rock (1) PctCover] DOUBLE ,
  [West Rim Trail (15) PctCover] DOUBLE ,
  [Wrangler Trail (4) PctCover] DOUBLE ,
  [Zion Scenic Drive (42) PctCover] DOUBLE 
)
